Accomadation/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Accomadation.Models
{
    public class Booking
    {
        public int UserId { get; set; }
        public bool Gender { get; set; }
        public int RoomId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}

Accomadation/Models/ErrorViewModel.cs
using System;

namespace Accomadation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Accomadation/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Accomadation.Models
{
    public class Room
    {
        public int ID { get; set; }        
        public byte Places { get; set; }
    }
}

Accomadation/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Accomadation.Models
{
    public class User
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Gender { get; set; } = false;        
    }
}

Accomadation/Controllers/BookingController.cs
using Accomadation.DTOs;
using Accomadation.Infrastructurs.Extentions;
using Accomadation.Infrastructurs.Interfaces.IServices;
using Accomadation.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Accomadation.Infrastructurs.Messages;
using System;

namespace Accomadation.Controllers
{
    public class BookingController : Controller
    {
        private readonly IUserService _userService;
        private readonly IRoomService _roomService;
        private readonly IBookingService _bookingService;
        public BookingController(IUserService userService
            , IRoomService roomService
            , IBookingService bookingService
            )
        {
            _userService = userService;
            _roomService = roomService;
            _bookingService = bookingService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await _bookingService.GetAsync();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> New()
        {
            var users = await _userService.GetAsync();
            TempData["Users"] = users.ToDrpUsers();
            var rooms = await _roomService.GetAsync();
            TempData["Rooms"] = rooms.ToDrpRooms();
            var model = await _bookingService.GetAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> New(BookingWriteDto data)
        {
            var message = Messages.InvalidModelData;
            if (data != null && !string.IsNullOrEmpty(data.User)
                && !string.IsNullOrEmpty(data.Room)
                && !string.IsNullOrEmpty(data.StartDate)
                && !string.IsNullOrEmpty(data.EndDate)
                && (data.Gender == "0" || data.Gender == "1")
                && (DateTime.Parse(data.StartDate) <= DateTime.Parse(data.EndDate))
                )
            {
                var b = new Booking();
                b.UserId = int.Parse(data.User);
                b.RoomId = int.Parse(data.Room);
                b.Gender = data.Gender == "0" ? false : true;// bool.Parse(data.Gender);
                b.StartDate = data.StartDate;
                b.EndDate = data.EndDate;
                message = await _bookingService.AddAsync(b);
            }
            var json = new JsonResult(message);
            return json;
        }

        [HttpGet]
        public async Task<IActionResult> FreeRooms()
        {
            var model = await _roomService.GetByDateAsync();
            return View(model);
        }

    }
}

Accomadation/Controllers/HomeController.cs
using Accomadation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Accomadation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Accomadation/Views/Booking/FreeRooms.cshtml
@model IEnumerable<Accomadation.DTOs.RoomReadDto>
@{
    ViewData["Title"] = "Free Rooms";
}
<div class="mb-3"><h2>Free Rooms</h2></div> 
<div class="d-flex justify-content-between mb-3">
    <div><button id="freeRoomFilter" class="btn-sm btn-outline-info mx-2">Filter</button></div>
    <div>
        <label> Date : </label>
        <input type="date" name="date" id="date" class="form-control-sm" />
    </div>
    <div></div>
</div>
<hr />
<table id="tblFreeRooms" class="table table-bordered table-responsive table-hover tbl-date-enter text-center  dt-responsive">
    <thead>
        <tr>
            <th>Room No</th>
            <th>Capacity</th>
            <th>Filled </th>
            <th>Remain</th>      
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.RoomId</td>
                <td> @item.Capacity</td>
                <td> @item.Filled</td>
                <td> @item.Remain</td>
                <td> @item.StartDate</td>                
                <td> @item.EndDate</td>
            </tr>
        }
    </tbody>
</table>




@section Scripts {
    <script type="text/javascript">

        $(() => {
            $('#tblFreeRooms').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });

    </script>
}

Accomadation/Views/Booking/Index.cshtml
@model IEnumerable<Accomadation.DTOs.BookingReadDto>
@{
    ViewData["Title"] = "Index";
}

<div class="mb-3"><h2>Current Booking</h2></div>
@*<div class="d-flex justify-content-between mb-3">
    <div><button id="newRoom" class="btn btn-outline-info mx-2">Make a new booking</button></div>
    <div><lael>Users : </lael> @Html.DropDownList("drpUsers", (List<SelectListItem>)TempData["Users"], new { @class = "form-control-sm" })</div>
</div>
<div id="messages"></div>
<div class="d-flex justify-content-between">
    <div>
        <label>Gender : </label>
        <select id="drpGender" class="form-control-sm">
            <option value="0">Man</option>
            <option value="1">Woman</option>
        </select>
    </div>
    <div>
        <label>RoomNo/Capacity : </label> @Html.DropDownList("drpRooms", (List<SelectListItem>)TempData["Rooms"], new { @class = "form-control-sm" })
    </div>
    <div>
        <label>Sart Date : </label>
        <input type="date" name="startDate" id="startDate" class="form-control-sm" />
    </div>
    <div>
        <label>End Date : </label>
        <input type="date" name="endDate" id="endDate" class="form-control-sm" />
    </div>
</div>
<hr />*@
<table id="tblBooking" class="table table-bordered table-responsive table-hover tbl-date-enter text-center  dt-responsive">
    <thead>
        <tr>
            <th>User Id</th>
            <th>Full Name</th>
            <th>Gender </th>
            <th>Room No</th>
            <th>Room Capacity</th>
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td> @item.UserId</td>
            <td> @item.FullName</td>
            <td> @item.Gender</td>
            <td> @item.RoomId</td>
            <td> @item.Capacity</td>
            <td> @item.StartDate</td>
            <td> @item.EndDate</td>
        </tr>
        }
    </tbody>
</table>




@section Scripts {
    <script type="text/javascript">

        $(() => {
            $('#tblBooking').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });



        $("#newRoom").on("click", () => {
            //alert()
            //$('#modalAddNewBooking').modal('show');
            var user = $("#drpUsers").val();
            var gender = $("#drpGender").val();
            var room = $("#drpRooms").val();
            var startDate = $("#startDate").val();
            var endDate = $("#endDate").val();

            var sDate = new Date(startDate);
            var eDate = new Date(endDate);

            var errMessage = "";
            var isValid = true;

            if (!startDate || !endDate) { errMessage = "Start Date And End Date Can't Be Empty !"; isValid = false }
            if (sDate > eDate) { errMessage = "Start Date Can't Be Greather Than End Date !"; isValid = false }
            if (!isValid) {
                callMessageHandler(errMessage, 2);
                return false;
            }

            var data = {
                "user": user,
                "gender": gender,
                "room": room,
                "startDate": startDate,
                "endDate": endDate
            }

            $.ajax({
                url: "/Booking/New",
                type: "POST",
                //contentType: "application/json; charset=utf-8",
                //dataType: "json",
                data: data,
                success: function (response) {
                    debugger;
                    if (response != null) {
                        //var successMessage = "Start Date And End Date Can't Be Empty !";
                        if (response.includes("success")) callMessageHandler(response);
                        else callMessageHandler(response, 2);
                    } else {
                        callMessageHandler(response, 2);
                    }
                },
                failure: function (response) {
                    //alert(response.responseText,);
                    callMessageHandler(response.responseText, 2);
                },
                error: function (response) {
                    //alert(response.responseText);
                    callMessageHandler(response.responseText, 2);
                }
            });

        });


        function callMessageHandler(message, alertType = 1) { //1=success ,2=danger
            var html = "";
            if (alertType == 1) {
                html += "<div class=\"alert alert-success\">" + message + "</div>"
            }
            if (alertType == 2) {
                html += "<div class=\"alert alert-danger\">" + message + "</div>"
            }
            $("#messages").html('').html(html)
                .fadeTo(10000, 500).slideUp(500, function () {
                    $("#messages").slideUp(500);
                });
        }

    </script>
}

Accomadation/Views/Booking/New.cshtml
@model IEnumerable<Accomadation.DTOs.BookingReadDto>
@{
    ViewData["Title"] = "New";
}

<div class="mb-3"><h2>Add New Booking</h2></div>
<div class="d-flex justify-content-between mb-3">
    <div><button id="newRoom" class="btn btn-outline-info mx-2">Make a new booking</button></div>
    <div><lael>Users : </lael> @Html.DropDownList("drpUsers", (List<SelectListItem>)TempData["Users"], new { @class = "form-control-sm" })</div>
</div>
<div id="messages"></div>
<div class="d-flex justify-content-between">
    <div>
        <label>Gender : </label>
        <select id="drpGender" class="form-control-sm">
            <option value="0">Man</option>
            <option value="1">Woman</option>
        </select>
    </div>
    <div>
        <label>RoomNo/Capacity : </label> @Html.DropDownList("drpRooms", (List<SelectListItem>)TempData["Rooms"], new { @class = "form-control-sm" })
    </div>
    <div>
        <label>Sart Date : </label>
        <input type="date" name="startDate" id="startDate" class="form-control-sm" />
    </div>
    <div>
        <label>End Date : </label>
        <input type="date" name="endDate" id="endDate" class="form-control-sm" />
    </div>
</div>
<hr />
@*<table id="tblBooking" class="table table-bordered table-responsive table-hover tbl-date-enter text-center  dt-responsive">
    <thead>
        <tr>
            <th>User Id</th>
            <th>Full Name</th>
            <th>Gender </th>
            <th>Room No</th>
            <th>Room Capacity</th>
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td> @item.UserId</td>
                <td> @item.FullName</td>
                <td> @item.Gender</td>
                <td> @item.RoomId</td>
                <td> @item.Capacity</td>
                <td> @item.StartDate</td>
                <td> @item.EndDate</td>
            </tr>
        }
    </tbody>
</table>*@




@section Scripts {
    <script type="text/javascript">

        //$(() => {
        //    $('#tblBooking').DataTable({
        //        "paging": true,
        //        "lengthChange": true,
        //        "searching": true,
        //        "ordering": true,
        //        "info": true,
        //        "autoWidth": true
        //    });
        //});



        $("#newRoom").on("click", () => {
            //alert()
            //$('#modalAddNewBooking').modal('show');
            var user = $("#drpUsers").val();
            var gender = $("#drpGender").val();
            var room = $("#drpRooms").val();
            var startDate = $("#startDate").val();
            var endDate = $("#endDate").val();

            var sDate = new Date(startDate);
            var eDate = new Date(endDate);

            var errMessage = "";
            var isValid = true;

            if (!startDate || !endDate) { errMessage = "Start Date And End Date Can't Be Empty !"; isValid = false }
            if (sDate > eDate) { errMessage = "Start Date Can't Be Greather Than End Date !"; isValid = false }
            if (!isValid) {
                callMessageHandler(errMessage, 2);
                return false;
            }

            var data = {
                "user": user,
                "gender": gender,
                "room": room,
                "startDate": startDate,
                "endDate": endDate
            }

            $.ajax({
                url: "/Booking/New",
                type: "POST",
                //contentType: "application/json; charset=utf-8",
                //dataType: "json",
                data: data,
                success: function (response) {
                    debugger;
                    if (response != null) {
                        //var successMessage = "Start Date And End Date Can't Be Empty !";
                        if (response.includes("success")) callMessageHandler(response);
                        else callMessageHandler(response, 2);
                    } else {
                        callMessageHandler(response, 2);
                    }
                },
                failure: function (response) {
                    //alert(response.responseText,);
                    callMessageHandler(response.responseText, 2);
                },
                error: function (response) {
                    //alert(response.responseText);
                    callMessageHandler(response.responseText, 2);
                }
            });

        });


        function callMessageHandler(message, alertType = 1) { //1=success ,2=danger
            var html = "";
            if (alertType == 1) {
                html += "<div class=\"alert alert-success\">" + message + "</div>"
            }
            if (alertType == 2) {
                html += "<div class=\"alert alert-danger\">" + message + "</div>"
            }
            $("#messages").html('').html(html)
                .fadeTo(10000, 500).slideUp(500, function () {
                    $("#messages").slideUp(500);
                });
        }

    </script>
}

Accomadation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Accomadation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Accomadation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Booking" asp-action="Index">Accomadation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="New">New Booking</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="FreeRooms">Free Rooms</a>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Accomadation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Bootstrap Datatable-->
    <script src="~/lib/DataTables1-10xx/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/DataTables1-10xx/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>